vars: {
	d2-config: {
		layout-engine: elk
		theme-id: 200
		center: true
		sketch: true
	}
}

coordinator: Coordinator
derivation-rs: Derivation: Converts nix outputs -> nix derivations

eval-rs: Eval: Evalutates nix expressions

store-rs-realise: Nix-store: Realises aka builds nix derivations

input -> coordinator: Flake URI

db: DB: Stores derivation paths (nix log, caching)

coordinator -> eval-rs
eval-rs -> coordinator: notifies
coordinator -> derivation-rs
derivation-rs -> coordinator: notifies
coordinator -> db: Derivation results
coordinator -> store-rs-realise
store-rs-realise -> coordinator: notifies

action

derivation1
derivation2

action -> derivation1
action -> derivation2
