vars: {
	d2-config: {
		layout-engine: elk
		theme-id: 200
		center: true
		sketch: true
	}
}

coordinator

evaluator

builder

input -> coordinator: Flake URI

database

coordinator -> evaluator: evaluates nix expression
evaluator -> coordinator: returns result
coordinator -> derivation: Converts the nix output paths to nix derivations
derivation -> coordinator: returns result
coordinator -> database: Stores derivation paths in database for `nix log` and for caching
coordinator -> builder: realises / builds store path
